const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Car,
		C3.Behaviors.EightDir,
		C3.Behaviors.Pin,
		C3.Plugins.Audio,
		C3.Behaviors.MoveTo,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Button.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{roads: 0},
	{portal1: 0},
	{Solid: 0},
	{wall: 0},
	{portal2: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Car: 0},
	{player1: 0},
	{"8Direction": 0},
	{NPC_1: 0},
	{concreteWall: 0},
	{NightTime: 0},
	{Pin: 0},
	{carAudio: 0},
	{sounds: 0},
	{NPC_2: 0},
	{NPC_3: 0},
	{NPC_4: 0},
	{NPC_5: 0},
	{NPC_6: 0},
	{NPC_8: 0},
	{NPC_9: 0},
	{NPC_10: 0},
	{NPC_11: 0},
	{NPC_12: 0},
	{NPC_13: 0},
	{NPC_14: 0},
	{NPC_15: 0},
	{NPC_16: 0},
	{NPC_17: 0},
	{NPC_18: 0},
	{NPC_19: 0},
	{NPC_20: 0},
	{MoveTo: 0},
	{POLICE1: 0},
	{POLICE2: 0},
	{NPC_21: 0},
	{POLICE3: 0},
	{NPC_Tele1: 0},
	{NPC_Tele2: 0},
	{NPC_Tele3: 0},
	{NPC_Tele4: 0},
	{COPY1: 0},
	{COPY2: 0},
	{COPY3: 0},
	{COPY4: 0},
	{COPY5: 0},
	{COPY7: 0},
	{COPY6: 0},
	{COPY8: 0},
	{carHonk: 0},
	{Keyboard: 0},
	{tunnel: 0},
	{blur: 0},
	{InvisWall: 0},
	{start: 0},
	{stop: 0},
	{Night: 0},
	{Blur2: 0},
	{Day: 0},
	{ControlsPage: 0},
	{Timer: 0},
	{seconds: 0},
	{Seconds: 0},
	{carStopper: 0},
	{sunset: 0},
	{sundown: 0},
	{lights: 0},
	{Start: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	roads: class extends self.ITilemapInstance {},
	portal1: class extends self.I3DShapeInstance {},
	wall: class extends self.I3DShapeInstance {},
	portal2: class extends self.I3DShapeInstance {},
	player1: class extends self.ISpriteInstance {},
	NPC_1: class extends self.ISpriteInstance {},
	concreteWall: class extends self.I3DShapeInstance {},
	NightTime: class extends self.ISpriteInstance {},
	carAudio: class extends self.ISpriteInstance {},
	sounds: class extends self.IInstance {},
	NPC_2: class extends self.ISpriteInstance {},
	NPC_3: class extends self.ISpriteInstance {},
	NPC_4: class extends self.ISpriteInstance {},
	NPC_5: class extends self.ISpriteInstance {},
	NPC_6: class extends self.ISpriteInstance {},
	NPC_8: class extends self.ISpriteInstance {},
	NPC_9: class extends self.ISpriteInstance {},
	NPC_10: class extends self.ISpriteInstance {},
	NPC_11: class extends self.ISpriteInstance {},
	NPC_12: class extends self.ISpriteInstance {},
	NPC_13: class extends self.ISpriteInstance {},
	NPC_14: class extends self.ISpriteInstance {},
	NPC_15: class extends self.ISpriteInstance {},
	NPC_16: class extends self.ISpriteInstance {},
	NPC_17: class extends self.ISpriteInstance {},
	NPC_18: class extends self.ISpriteInstance {},
	NPC_19: class extends self.ISpriteInstance {},
	NPC_20: class extends self.ISpriteInstance {},
	POLICE1: class extends self.ISpriteInstance {},
	POLICE2: class extends self.ISpriteInstance {},
	NPC_21: class extends self.ISpriteInstance {},
	POLICE3: class extends self.ISpriteInstance {},
	NPC_Tele1: class extends self.ISpriteInstance {},
	NPC_Tele2: class extends self.ISpriteInstance {},
	NPC_Tele3: class extends self.ISpriteInstance {},
	NPC_Tele4: class extends self.ISpriteInstance {},
	COPY1: class extends self.ISpriteInstance {},
	COPY2: class extends self.ISpriteInstance {},
	COPY3: class extends self.ISpriteInstance {},
	COPY4: class extends self.ISpriteInstance {},
	COPY5: class extends self.ISpriteInstance {},
	COPY7: class extends self.ISpriteInstance {},
	COPY6: class extends self.ISpriteInstance {},
	COPY8: class extends self.ISpriteInstance {},
	carHonk: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	tunnel: class extends self.ISpriteInstance {},
	blur: class extends self.ISpriteInstance {},
	InvisWall: class extends self.ISpriteInstance {},
	start: class extends self.IButtonInstance {},
	stop: class extends self.ISpriteInstance {},
	Night: class extends self.IButtonInstance {},
	Blur2: class extends self.ISpriteInstance {},
	Day: class extends self.IButtonInstance {},
	ControlsPage: class extends self.ISpriteInstance {},
	Timer: class extends self.ITextInstance {},
	Seconds: class extends self.ITextInstance {},
	carStopper: class extends self.ISpriteInstance {},
	sunset: class extends self.ISpriteInstance {},
	sundown: class extends self.IButtonInstance {},
	lights: class extends self.ISpriteInstance {}
}